[package]
name = "RustConsoleEmulator"
version = "0.1.0"
authors = ["Shawn Hice <shawn.hice@autodesk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
